prompt --application/shared_components/user_interface/lovs/lov_articulos_presu
begin
--   Manifest
--     LOV_ARTICULOS_PRESU
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.0'
,p_default_workspace_id=>2715162693355865
,p_default_application_id=>122
,p_default_id_offset=>0
,p_default_owner=>'INV'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(257641123557959036)
,p_lov_name=>'LOV_ARTICULOS_PRESU'
,p_lov_query=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT A.DESCRIPCION,A.COD_ARTICULO,1 CANTIDAD,COD_RUBRO',
'FROM ST_ARTICULOS A,VT_ORIGENES T,VT_ORDENES_TRABAJO V',
'WHERE A.COD_EMPRESA=:P_COD_EMPRESA AND COD_RUBRO=''MO'' AND T.COD_ORIGEN=V.COD_ORIGEN AND T.COD_EMPRESA=V.COD_EMPRESA AND V.COD_EMPRESA=A.COD_EMPRESA AND V.TIP_COMPROBANTE=:P342_TIP_COMPROBANTE_REF AND V.SER_COMPROBANTE=:P342_SER_COMPROBANTE_REF AND V.'
||'NRO_COMPROBANTE=:P342_NRO_COMPROBANTE_REF AND A.TIPO_MO=T.ORIGEN AND T.ORIGEN=''STNGO'' AND TIPO_MO IS NOT NULL AND NVL(ESTADO,''S'') NOT IN (''I'',''N'') AND NVL(A.IND_PARTICULAR,''X'')<>NVL(V.IND_GARANTIA,''Z'') AND (COD_LINEA=NVL((SELECT AA.COD_LINEA FROM ST_'
||'ARTICULOS AA WHERE AA.COD_EMPRESA=:P_COD_EMPRESA AND AA.COD_ARTICULO=V.COD_ARTICULO),COD_LINEA)) AND NVL(COD_MARCA,:P342_COD_MARCA)=:P342_COD_MARCA',
'UNION ALL',
'SELECT A.DESCRIPCION,A.COD_ARTICULO,1 CANTIDAD,COD_RUBRO',
'FROM ST_ARTICULOS A,VT_ORIGENES T,VT_ORDENES_TRABAJO V',
'WHERE A.COD_EMPRESA=:P_COD_EMPRESA AND COD_RUBRO=''MO'' AND T.COD_ORIGEN=V.COD_ORIGEN AND T.COD_EMPRESA=V.COD_EMPRESA AND V.COD_EMPRESA=A.COD_EMPRESA AND V.TIP_COMPROBANTE=:P342_TIP_COMPROBANTE_REF AND V.SER_COMPROBANTE=:P342_SER_COMPROBANTE_REF AND V.'
||'NRO_COMPROBANTE=:P342_NRO_COMPROBANTE_REF AND T.ORIGEN=''STNGO'' AND A.TIPO_MO=T.ORIGEN AND NVL(ESTADO,''S'') NOT IN (''I'',''N'') AND NVL(A.IND_PARTICULAR,''X'')<>NVL(V.IND_GARANTIA,''Z'') AND (COD_CATEGORIA=NVL((SELECT AA.COD_CATEGORIA FROM ST_ARTICULOS AA WHE'
||'RE AA.COD_EMPRESA=:P_COD_EMPRESA AND AA.COD_ARTICULO=V.COD_ARTICULO),COD_CATEGORIA)) AND A.COD_LINEA IS NULL AND TIPO_MO IS NOT NULL AND NVL(COD_MARCA,:P342_COD_MARCA)=:P342_COD_MARCA',
'UNION ALL',
'SELECT A.DESCRIPCION,A.COD_ARTICULO,1 CANTIDAD,COD_RUBRO',
'FROM ST_ARTICULOS A,VT_ORIGENES T,VT_ORDENES_TRABAJO V',
'WHERE A.COD_EMPRESA=:P_COD_EMPRESA AND COD_RUBRO=''MO'' AND NVL(ESTADO,''S'') NOT IN (''I'',''N'') AND T.COD_ORIGEN=V.COD_ORIGEN AND T.COD_EMPRESA=V.COD_EMPRESA AND V.COD_EMPRESA=A.COD_EMPRESA AND V.TIP_COMPROBANTE=:P342_TIP_COMPROBANTE_REF AND V.SER_COMPROB'
||'ANTE=:P342_SER_COMPROBANTE_REF AND V.NRO_COMPROBANTE=:P342_NRO_COMPROBANTE_REF AND NVL(A.IND_PARTICULAR,''X'')<>NVL(V.IND_GARANTIA,''Z'') AND T.ORIGEN=''STNGO'' AND A.TIPO_MO=''STNGO'' AND TIPO_MO IS NOT NULL AND COD_CATEGORIA IS NULL AND A.COD_LINEA IS NULL'
||' AND NVL(COD_MARCA,:P342_COD_MARCA)=:P342_COD_MARCA',
'UNION ALL',
'SELECT A.DESCRIPCION,A.COD_ARTICULO,1 CANTIDAD,COD_RUBRO',
'FROM ST_ARTICULOS A,VT_ORIGENES T,VT_ORDENES_TRABAJO V',
'WHERE A.COD_EMPRESA=:P_COD_EMPRESA AND COD_RUBRO=''MO'' AND NVL(ESTADO,''S'') NOT IN (''I'',''N'') AND T.COD_ORIGEN=V.COD_ORIGEN AND T.COD_EMPRESA=V.COD_EMPRESA AND V.COD_EMPRESA=A.COD_EMPRESA AND V.TIP_COMPROBANTE=:P342_TIP_COMPROBANTE_REF AND V.SER_COMPROB'
||'ANTE=:P342_SER_COMPROBANTE_REF AND V.NRO_COMPROBANTE=:P342_NRO_COMPROBANTE_REF AND NVL(T.ORIGEN,''X'') NOT IN ''STNGO'' AND A.TIPO_MO NOT IN ''STNGO'' AND TIPO_MO IS NOT NULL AND NVL(COD_MARCA,:P342_COD_MARCA)=:P342_COD_MARCA',
'',
'UNION ALL',
'SELECT A.DESCRIPCION,A.COD_ARTICULO,NVL((select SUM(E.CANT_DISPON)',
'             from ST_EXISTENCIA_ART E',
'            where E.COD_EMPRESA= :P_COD_EMPRESA',
'              AND A.COD_ARTICULO = E.COD_ARTICULO',
'              AND E.COD_SUCURSAL in (''101'', ''190'')),0) CANTIDAD,A.COD_RUBRO',
'FROM ST_ARTICULOS A, VT_ORDENES_TRABAJO V,ST_EQUIVALENCIA_ART S',
'WHERE A.COD_EMPRESA=:P_COD_EMPRESA AND NVL(A.ESTADO,''N'')<>''I''  AND V.COD_EMPRESA=A.COD_EMPRESA AND V.TIP_COMPROBANTE=:P342_TIP_COMPROBANTE_REF AND V.SER_COMPROBANTE=:P342_SER_COMPROBANTE_REF AND V.NRO_COMPROBANTE=:P342_NRO_COMPROBANTE_REF',
'AND V.COD_ARTICULO=S.COD_ARTICULO AND V.COD_EMPRESA=S.COD_EMPRESA AND S.COD_ARTICULO_EQUI=A.COD_ARTICULO',
'GROUP BY A.DESCRIPCION,A.COD_ARTICULO,A.COD_RUBRO',
'',
'',
'ORDER BY 3;'))
,p_source_type=>'SQL'
,p_location=>'LOCAL'
,p_use_local_sync_table=>false
,p_return_column_name=>'COD_ARTICULO'
,p_display_column_name=>'DESCRIPCION'
,p_group_sort_direction=>'ASC'
,p_default_sort_direction=>'ASC'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(257642139832954401)
,p_query_column_name=>'COD_ARTICULO'
,p_heading=>'Cod articulo'
,p_display_sequence=>10
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(257641756309954402)
,p_query_column_name=>'DESCRIPCION'
,p_heading=>'Descripcion'
,p_display_sequence=>20
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(257642554116954401)
,p_query_column_name=>'CANTIDAD'
,p_heading=>'Stock (101-190)'
,p_display_sequence=>30
,p_data_type=>'NUMBER'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(257642953066954401)
,p_query_column_name=>'COD_RUBRO'
,p_heading=>'Cod Rubro'
,p_display_sequence=>40
,p_data_type=>'VARCHAR2'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp.component_end;
end;
/
