prompt --application/shared_components/user_interface/lovs/lv_vehiculo_rpplaped
begin
--   Manifest
--     LV_VEHICULO_RPPLAPED
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.0'
,p_default_workspace_id=>2715162693355865
,p_default_application_id=>122
,p_default_id_offset=>0
,p_default_owner=>'INV'
);
wwv_flow_imp_shared.create_list_of_values(
 p_id=>wwv_flow_imp.id(99206271110692763)
,p_lov_name=>'LV_VEHICULO_RPPLAPED'
,p_lov_query=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Select cod_vehiculo||'' - ''||descripcion d, tipo, volumen,chapa,peso_kg,largo,alto,ancho,marca , cod_vehiculo R',
'from rp_vehiculos',
'where cod_empresa = :P_COD_EMPRESA',
' ',
'and NVL(:P358_TOT_VOLUMEN ,''0'')<=nvl(volumen,0);'))
,p_source_type=>'SQL'
,p_location=>'LOCAL'
,p_use_local_sync_table=>false
,p_return_column_name=>'R'
,p_display_column_name=>'D'
,p_group_sort_direction=>'ASC'
,p_default_sort_column_name=>'D'
,p_default_sort_direction=>'ASC'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99208950780754689)
,p_query_column_name=>'R'
,p_display_sequence=>10
,p_data_type=>'VARCHAR2'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99209312393754689)
,p_query_column_name=>'D'
,p_heading=>'VEHICULO'
,p_display_sequence=>20
,p_data_type=>'VARCHAR2'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99209722126754689)
,p_query_column_name=>'TIPO'
,p_heading=>'Tipo'
,p_display_sequence=>30
,p_data_type=>'VARCHAR2'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99210164276754690)
,p_query_column_name=>'VOLUMEN'
,p_heading=>'Volumen'
,p_display_sequence=>40
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99210577472754690)
,p_query_column_name=>'CHAPA'
,p_heading=>'Chapa'
,p_display_sequence=>50
,p_data_type=>'VARCHAR2'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99210949323754690)
,p_query_column_name=>'PESO_KG'
,p_heading=>'Peso Kg'
,p_display_sequence=>60
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99211326939754690)
,p_query_column_name=>'LARGO'
,p_heading=>'Largo'
,p_display_sequence=>70
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99211750542754690)
,p_query_column_name=>'ALTO'
,p_heading=>'Alto'
,p_display_sequence=>80
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99212180545754690)
,p_query_column_name=>'ANCHO'
,p_heading=>'Ancho'
,p_display_sequence=>90
,p_data_type=>'NUMBER'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp_shared.create_list_of_values_cols(
 p_id=>wwv_flow_imp.id(99212501824754690)
,p_query_column_name=>'MARCA'
,p_heading=>'Marca'
,p_display_sequence=>100
,p_data_type=>'VARCHAR2'
,p_is_visible=>'N'
,p_is_searchable=>'N'
);
wwv_flow_imp.component_end;
end;
/
